language: minimal

services:
    - docker

env:
    global:
        - CACHE_DIR="build/cache"
        - DOCKER_IMAGE="docker_image"

cache:
    directories:
        - "$CACHE_DIR"

before_script:
    - |
        if [[ -f "$CACHE_DIR/docker.tar" ]]; then
            docker load -i "$CACHE_DIR/docker.tar"
        fi
    - docker build -t "$DOCKER_IMAGE" --pull .

before_cache:
    - mkdir -p "$CACHE_DIR"
    - docker save -o "$CACHE_DIR/docker.tar" $(docker history -q "$DOCKER_IMAGE" | grep -v "<" | tail -n +3)


script:
    - |
        docker run --rm "$DOCKER_IMAGE" /bin/bash -c '
            set -e

            echo -e "\n\e[1;97;44m > Dumping environment... \e[0m"
            pacman --color=always -Q
            vcpkg list

            export CXXFLAGS="-fuse-ld=gold -fdiagnostics-color=always -Werror "
            CXXFLAGS+="-isystem /opt/vcpkg/installed/x64-linux/include -L/opt/vcpkg/installed/x64-linux/lib "
            export CLICOLOR_FORCE="1"

            echo -e "\n\e[1;97;44m > Building debug... \e[0m"
            mkdir -p "build/debug"
            cd "build/debug"
            cmake -G Ninja "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Debug" "../.."
            ninja
            echo

            echo -e "\n\e[1;97;44m > Building release... \e[0m"
            mkdir "../release"
            cd "../release"
            cmake -G Ninja "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Release" "../.."
            ninja
            echo


            err=0

            echo -e "\n\e[1;97;44m > Checking style with clang-format... \e[0m"
            while IFS= read -r f; do
                diff=$(clang-format "$f" | diff -d --color=always "$f" - ||:)
                if [[ ! -z "$diff" ]]; then
                    echo -e "\e[1m$f\e[0m"
                    echo "$diff"
                    echo
                    ((++err))
                fi
            done < <(git ls-files | grep -E "\.(cpp|h)$")

            echo -e "\n\e[1;97;44m > Checking with clang-tidy... \e[0m"
            CXXFLAGS+="-w"
            mkdir -p "build/clang-tidy"
            cd "build/clang-tidy"
            cmake -G Ninja "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake" "../.."
            ninja
            SRC="$(git ls-files '../..' | grep -E '\.cpp$')"
            clang-tidy -quiet -p "compile_commands.json" -warnings-as-errors "*" $SRC
            ((err += $?))

            if [[ "$err" -ne "0" ]]; then
                exit "$err"
            fi
        '
