version: 2.1

jobs:
  "nothing":
    docker:
      - image: alpine:3.9
    steps:
      - run:
          name: Do nothing
          command: ":"

workflows:
  version: 2
  nothing:
    jobs:
      - "nothing":
          filters:
            branches:
              only: none
