version: 2
jobs:
  build:
    docker:
      - image: kiwixz/arch-vcpkg:2019-02-17
    environment:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - checkout
      - restore_cache:
          name: Restoring pacman cache
          keys:
            - packages-0-{{ .Branch }}-{{ .Revision }}
            - packages-0-{{ .Branch }}-
            - packages-0-
      - run:
          name: Installing system dependencies
          command: |
            pacman --color=always --needed --noconfirm -Sy  \
                clang cmake lld ninja python3  \
                libxcursor libxinerama libxrandr  `# glfw`  \
                nasm  `# x265`
            ln -s "/opt/vcpkg"
      - save_cache:
          name: Saving vcpkg cache
          key: packages-0-{{ .Branch }}-{{ .Revision }}
          paths:
            - /var/cache/pacman/pkg
      - restore_cache:
          name: Restoring vcpkg cache
          keys:
            - vcpkg-0-{{ .Branch }}-{{ .Revision }}
            - vcpkg-0-{{ .Branch }}-
            - vcpkg-0-
      - run:
          name: Installing vcpkg dependencies
          command: |
            ./install_libs.py
            kiwixz_cleanup_vcpkg
      - save_cache:
          name: Saving vcpkg cache
          key: vcpkg-0-{{ .Branch }}-{{ .Revision }}
          paths:
            - /opt/vcpkg
      - run:
          name: Testing debug
          command: |
            export CXXFLAGS="-fdiagnostics-color=always -Werror"
            export LDFLAGS="-fdiagnostics-color=always -Werror -fuse-ld=lld"
            export ASAN_OPTIONS="check_initialization_order=1"
            export UBSAN_OPTIONS="print_stacktrace=1"
            mkdir -p "build/debug"
            cd "build/debug"
            cmake -G Ninja -D "CMAKE_BUILD_TYPE=Debug" "../.."
            ninja
            ctest --output-on-failure -E "check_.*"
      - run:
          name: Testing release
          command: |
            export CXXFLAGS="-fdiagnostics-color=always -Werror"
            export LDFLAGS="-fdiagnostics-color=always -Werror -fuse-ld=lld"
            mkdir -p "build/release"
            cd "build/release"
            cmake -G Ninja -D "CMAKE_BUILD_TYPE=Release" "../.."
            ninja
            ctest --output-on-failure -E "check_.*"
      - run:
          name: Additional checks
          command: |
            cd "build/debug"
            ctest --output-on-failure -R "check_.*"
